name = "my-dispatcher"
main = "index.js" # Adjust to the actual location of index.js
compatibility_date = "2025-01-13"

[durable_objects]
bindings = [
  { name = "MyDurableObject", class_name = "MyDurableObject" }
]

[[dispatch_namespaces]]
binding = "dispatcher"
namespace = "staging-namespace"
